name: Update tree

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.2.0
        with:
          provider: aws # default is linode
          region: 'eu-central-1'
      - name: Run
        run: |
          ./pipeline.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: MpxBot # defaults to "github-actions[bot]"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

      - name: Upload
        run: |
          source upload.sh
        env: 
          MYKEY: ${{ secrets.DO_SECRET }}
